# Generated by Django 6.1 on 2026-08-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=150)),
                ('crop', models.CharField(default='All Crops', max_length=100)),
                ('content', models.TextField()),
                ('time_ago', models.CharField(default='Just now', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_rental', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('is_scientist', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.forumpost')),
            ],
        ),
    ]
