# Generated by Django 6.1 on 2026-08-24 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postreply',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('crop_problem', 'Crop Problem'), ('disease', 'Disease'), ('pest', 'Pest'), ('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('seeds', 'Seeds'), ('market_price', 'Market Price'), ('weather', 'Weather'), ('govt_scheme', 'Government Scheme'), ('machinery', 'Machinery'), ('general', 'General Farming'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreply',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='postreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postreply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='postreply',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('misleading', 'Misleading Farming Information'), ('abusive', 'Abusive Language'), ('inappropriate', 'Inappropriate Content'), ('advertisement', 'Advertisement'), ('scam', 'Scam'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('actioned', 'Action Taken')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.forumpost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.postreply')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MachineryListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('tractor', 'Tractor'), ('combine_harvester', 'Combine Harvester'), ('rotavator', 'Rotavator'), ('seed_drill', 'Seed Drill'), ('drone_sprayer', 'Drone Sprayer'), ('power_tiller', 'Power Tiller'), ('cultivator', 'Cultivator'), ('sprayer', 'Sprayer'), ('thresher', 'Thresher'), ('other', 'Other')], max_length=30)),
                ('machine_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('locality', models.CharField(blank=True, default='', max_length=150)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('availability', models.CharField(blank=True, default='Available', max_length=200)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_acre', 'Per Acre'), ('negotiable', 'Negotiable')], default='per_day', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machinery_images/')),
                ('contact_method', models.CharField(blank=True, default='Contact via community reply', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Currently Rented'), ('unavailable', 'Unavailable'), ('removed', 'Removed')], default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='community.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
