# Generated by Django 6.1 on 2026-08-23 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(default='Ramesh Patel', max_length=100)),
                ('name_native', models.CharField(blank=True, default='రమేష్ పటేల్', max_length=100)),
                ('village', models.CharField(default='Pedakakani', max_length=150)),
                ('district', models.CharField(default='Guntur', max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('total_land', models.CharField(default='6.5 Acres', max_length=50)),
                ('soil_type', models.CharField(default='Black Clay Loam (నల్లరేగడి నేల)', max_length=100)),
                ('irrigation_source', models.CharField(default='Borewell + Canal', max_length=100)),
                ('active_crops', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='farmer_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
