# Generated by Django 6.1 on 2026-08-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, default='+91 98765 43210', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
