# Generated by Django 6.1 on 2026-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('category', models.CharField(default='Central Scheme', max_length=100)),
                ('benefit_amount', models.CharField(max_length=150)),
                ('eligibility', models.TextField()),
                ('required_documents', models.JSONField(default=list)),
                ('application_status', models.CharField(default='Applications Open', max_length=100)),
                ('official_portal_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
