# Generated by Django 6.1 on 2026-08-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Guntur District, AP', max_length=150)),
                ('temperature', models.CharField(default='32°C', max_length=20)),
                ('feels_like', models.CharField(default='36°C', max_length=20)),
                ('condition', models.CharField(default='Partly Cloudy', max_length=100)),
                ('humidity', models.CharField(default='68%', max_length=20)),
                ('wind_speed', models.CharField(default='14 km/h', max_length=20)),
                ('rain_probability', models.CharField(default='20%', max_length=20)),
                ('uv_index', models.CharField(default='High', max_length=20)),
                ('advisory_headline', models.CharField(default='Agro-Advisory: Moderate Rain expected Sunday & Monday', max_length=255)),
                ('advisory_detail', models.TextField(default='Hold pesticide/fertilizer spraying until Tuesday to avoid chemical wash-off. Ensure field drainage channels are clear for standing cotton & chilli crops.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('rain', models.CharField(max_length=20)),
                ('icon', models.CharField(default='CloudSun', max_length=50)),
                ('weather_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_days', to='weather_advisory.weatherreport')),
            ],
        ),
    ]
