# Generated by Django 6.1 on 2026-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropDiseaseKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_name_native', models.CharField(blank=True, max_length=100)),
                ('disease_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('severity', models.CharField(default='Moderate', max_length=50)),
                ('confidence_default', models.FloatField(default=95.0)),
                ('symptoms', models.TextField()),
                ('organic_solution', models.TextField()),
                ('chemical_solution', models.TextField()),
                ('prevention_advice', models.TextField()),
                ('sample_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeafScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaf_scans/')),
                ('crop_detected', models.CharField(max_length=100)),
                ('disease_detected', models.CharField(max_length=150)),
                ('confidence', models.FloatField(default=96.0)),
                ('severity', models.CharField(default='Moderate', max_length=50)),
                ('organic_solution', models.TextField(blank=True)),
                ('chemical_solution', models.TextField(blank=True)),
                ('prevention_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
