# Generated by Django 6.1 on 2026-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='chemical_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='crop_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='crop_name_native',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='disease_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='organic_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='prevention_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='severity',
            field=models.CharField(default='Moderate', max_length=100),
        ),
        migrations.AlterField(
            model_name='cropdiseaseknowledge',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='crop_detected',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='disease_detected',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='severity',
            field=models.CharField(default='Moderate', max_length=100),
        ),
    ]
