# Generated by Django 6.1 on 2026-08-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detection', '0002_alter_cropdiseaseknowledge_chemical_solution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leafscanhistory',
            name='category',
            field=models.CharField(default='Foliar Pathology', max_length=100),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='confidence_level',
            field=models.CharField(default='high', max_length=50),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='crop_scientific_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='diagnosis_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='disease_scientific_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='source',
            field=models.CharField(default='claude_vision', max_length=100),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='status',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaf_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leafscanhistory',
            name='warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='chemical_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='confidence',
            field=models.FloatField(default=95.0),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='organic_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leafscanhistory',
            name='prevention_advice',
            field=models.TextField(blank=True, default=''),
        ),
    ]
