# Generated by Django 6.1 on 2026-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandiCommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=120)),
                ('crop_name_native', models.CharField(blank=True, max_length=120)),
                ('mandi_name', models.CharField(max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('modal_price', models.IntegerField(help_text='Price in INR per Quintal')),
                ('previous_price', models.IntegerField(help_text='Previous day price')),
                ('price_change_percent', models.CharField(default='+0.0%', max_length=20)),
                ('msp_rate', models.IntegerField(help_text='Minimum Support Price')),
                ('daily_arrival', models.CharField(default='500 Quintals', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
